### ISSUE TITLE
ui(news): Decoupling and updating code structure

### ISSUE THREAD

**Issue by mahieyin-rahmun** [AGenCyLab/agencylab.github.io#18]
### Gist
The news section of the website needs to be modified so that there is dependency only on the news content and not on writing the markup itself.

### General Flow
The general flow will be:
1. There will be a json file that will contain the news data
2. When the webpage launches, it will read the json file and generate the HTML markup for each news with uniform CSS styling
3. If a maintainer wants to add a news, all they should need to do is just modify the json file.

### The JSON file structure
Something like the following can be thought of as the initial JSON data file structure:
```
[
  {
    "date": "09/02/2021",
    "newsTitle": "Traffic Forecasting paper accepted at PAKDD-2021",
    "newsDescription": "Our Traffic Forecasting paper "SST-GNN: Simplified Spatio-temporal Traffic forecasting model using Graph Neural Network", has been accepted in 25th Pacific-Asia Conference on Knowledge Discovery and Data Mining (PAKDD-2021)(Core Rank: A). Congratulations to Amit and Kashob.",
    "newsImage": "path/to/image.png" // // can be undefined
    "newsLink": "www.link.to.content.com/content.pdf"  // can be undefined
  },
  {
    ...
  }
]
```

### Tasks
- [x] Create a News component
- [x] Refactor existing news data to json file
- [x] Read JSON file and generate markup when the news.html page is loaded
- [x] Styling

### Additional Suggestions
@saif-mahmud vaiya, @thTonmoy vaiya and others, feel free to leave suggestions/comments.
